<?xml version="1.0" encoding="utf-8"?><Database Name="DbWS" Class="DbWSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=DbWS;Integrated Security=True" SettingsObjectName="Book_Library.Properties.Settings" SettingsPropertyName="DbWSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTPhieuDatHang" Member="CTPhieuDatHangs">
    <Type Name="CTPhieuDatHang">
      <Column Name="MaPDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaTien" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDatHang_CTPhieuDatHang" Member="PhieuDatHang" ThisKey="MaPDH" OtherKey="MaPDH" Type="PhieuDatHang" IsForeignKey="true" />
      <Association Name="Sach_CTPhieuDatHang" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuGiaoHang" Member="CTPhieuGiaoHangs">
    <Type Name="CTPhieuGiaoHang">
      <Column Name="MaPGH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GiaTienVC" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Trangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDatHang_CTPhieuGiaoHang" Member="PhieuDatHang" ThisKey="MaPDH" OtherKey="MaPDH" Type="PhieuDatHang" IsForeignKey="true" />
      <Association Name="PhieuGiaoHang_CTPhieuGiaoHang" Member="PhieuGiaoHang" ThisKey="MaPGH" OtherKey="MaPGH" Type="PhieuGiaoHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuNhapKho" Member="CTPhieuNhapKhos">
    <Type Name="CTPhieuNhapKho">
      <Column Name="MaPN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuNhapKho_CTPhieuNhapKho" Member="PhieuNhapKho" ThisKey="MaPN" OtherKey="MaPN" Type="PhieuNhapKho" IsForeignKey="true" />
      <Association Name="Sach_CTPhieuNhapKho" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhuyenMai" Member="KhuyenMais">
    <Type Name="KhuyenMai">
      <Column Name="MaKM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTriGiam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayApDung" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="KhuyenMai_Sach" Member="Saches" ThisKey="MaKM" OtherKey="MaKM" Type="Sach" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="TenDN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Trangthai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NguoiDung_PhieuDatHang" Member="PhieuDatHangs" ThisKey="TenDN" OtherKey="TaiKhoanNM" Type="PhieuDatHang" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Trangthai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_PhieuDatHang" Member="PhieuDatHangs" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuDatHang" />
      <Association Name="NhanVien_PhieuGiaoHang" Member="PhieuGiaoHangs" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuGiaoHang" />
      <Association Name="NhanVien_PhieuNhapKho" Member="PhieuNhapKhos" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuNhapKho" />
      <Association Name="Quyen_NhanVien" Member="Quyen" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="Quyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDatHang" Member="PhieuDatHangs">
    <Type Name="PhieuDatHang">
      <Column Name="MaPDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoanNM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTenNN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayDH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayDuyetHang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhieuDatHang_CTPhieuDatHang" Member="CTPhieuDatHangs" ThisKey="MaPDH" OtherKey="MaPDH" Type="CTPhieuDatHang" />
      <Association Name="PhieuDatHang_CTPhieuGiaoHang" Member="CTPhieuGiaoHangs" ThisKey="MaPDH" OtherKey="MaPDH" Type="CTPhieuGiaoHang" />
      <Association Name="NguoiDung_PhieuDatHang" Member="NguoiDung" ThisKey="TaiKhoanNM" OtherKey="TenDN" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuDatHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuGiaoHang" Member="PhieuGiaoHangs">
    <Type Name="PhieuGiaoHang">
      <Column Name="MaPGH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhanGH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayDuyetGH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhieuGiaoHang_CTPhieuGiaoHang" Member="CTPhieuGiaoHangs" ThisKey="MaPGH" OtherKey="MaPGH" Type="CTPhieuGiaoHang" />
      <Association Name="NhanVien_PhieuGiaoHang" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhapKho" Member="PhieuNhapKhos">
    <Type Name="PhieuNhapKho">
      <Column Name="MaPN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PhieuNhapKho_CTPhieuNhapKho" Member="CTPhieuNhapKhos" ThisKey="MaPN" OtherKey="MaPN" Type="CTPhieuNhapKho" />
      <Association Name="NhanVien_PhieuNhapKho" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trangthai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Quyen_NhanVien" Member="NhanViens" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NhaXuatBan" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SoTrang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamXuatBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GiaVon" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="LoaiBia" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PhanTramLoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Trangthai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Sach_CTPhieuDatHang" Member="CTPhieuDatHangs" ThisKey="MaSach" OtherKey="MaSach" Type="CTPhieuDatHang" />
      <Association Name="Sach_CTPhieuNhapKho" Member="CTPhieuNhapKhos" ThisKey="MaSach" OtherKey="MaSach" Type="CTPhieuNhapKho" />
      <Association Name="KhuyenMai_Sach" Member="KhuyenMai" ThisKey="MaKM" OtherKey="MaKM" Type="KhuyenMai" IsForeignKey="true" />
      <Association Name="TheLoai_Sach" Member="TheLoai" ThisKey="MaTL" OtherKey="MaTL" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaTL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trangthai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TheLoai_Sach" Member="Saches" ThisKey="MaTL" OtherKey="MaTL" Type="Sach" />
    </Type>
  </Table>
</Database>